language: java

dist: trusty

matrix:
  include:
  - jdk: openjdk8
    env: ADDITIONAL_MAVEN_ARGS="-P enable-jacoco -P enable-mutation-testing -P enable-coveralls"

addons:
  sonarcloud:
    organization: leonardoscommegna
    token:
      secure: $SONAR_TOKEN

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - mvn -f schoolmanager-aggregator/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS sonar:sonar -Dsonar.projectKey=LeonardoScommegna_schoolmanager